import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroSection from '@/components/sections/HeroSection';
import Navbar from '@/components/sections/Navbar';
import Footer from '@/components/sections/Footer';
import Testimonials from '@/components/Testimonials';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <HeroSection />
        {children}
        <Testimonials />
        <Footer />
      </body>
    </html>
  );
}
